#!/usr/bin/env python

import re
import sys
from main import app

def main():
    """
    Wrapper for the Typer app to ensure correct execution context.
    """
    # The app() call is what Typer uses to parse args and run commands.
    app()

if __name__ == '__main__':
    # This allows the script to be run directly.
    # The following lines are good practice for entry-point scripts.
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
