from pathlib import Path
from typing import Any, Protocol, runtime_checkable

from ..models.graph import QuipuNode
from .storage import HistoryReader, HistoryWriter


@runtime_checkable
class QuipuEngine(Protocol):
    root_dir: Path
    reader: HistoryReader
    writer: HistoryWriter
    history_graph: dict[str, QuipuNode]
    current_node: QuipuNode | None
    git_db: Any

    def align(self) -> str: ...
    def visit(self, target_hash: str) -> None: ...
    def capture_drift(self, current_hash: str, message: str | None = None) -> QuipuNode: ...
    def create_plan_node(
        self, input_tree: str, output_tree: str, plan_content: str, summary_override: str | None = None
    ) -> QuipuNode: ...
    def checkout(self, target_hash: str) -> None: ...
    def back(self) -> str | None: ...
    def forward(self) -> str | None: ...
    def find_nodes(
        self, summary_regex: str | None = None, node_type: str | None = None, limit: int = 10
    ) -> list[QuipuNode]: ...
    def close(self) -> None: ...
