from typing import Any, Protocol, runtime_checkable

from ..models.graph import QuipuNode


@runtime_checkable
class HistoryReader(Protocol):
    def load_all_nodes(self) -> list[QuipuNode]: ...
    def get_node_content(self, node: QuipuNode) -> str: ...
    def get_node_blobs(self, commit_hash: str) -> dict[str, bytes]: ...
    def find_nodes(
        self, summary_regex: str | None = None, node_type: str | None = None, limit: int = 10
    ) -> list[QuipuNode]: ...
    def get_node_count(self) -> int: ...
    def load_nodes_paginated(self, limit: int, offset: int) -> list[QuipuNode]: ...
    def get_ancestor_output_trees(self, start_output_tree_hash: str) -> set[str]: ...
    def get_private_data(self, node_commit_hash: str) -> str | None: ...
    def get_descendant_output_trees(self, start_output_tree_hash: str) -> set[str]: ...
    def get_node_position(self, output_tree_hash: str) -> int: ...


@runtime_checkable
class HistoryWriter(Protocol):
    def create_node(
        self, node_type: str, input_tree: str, output_tree: str, content: str, **kwargs: Any
    ) -> QuipuNode: ...
